import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Providers from "./providers";
import AuthBootstrap from "./AuthBootstrap";
import ToastProvider from "@/components/ui/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ToastProvider>
            <nav className="w-full border-b">
              <div className="mx-auto max-w-5xl p-3 flex gap-4 text-sm">
                <Link href="/">Home</Link>
                <Link href="/bubbles">Bubbles</Link>
                <Link href="/auth" className="ml-auto">Auth</Link>
                <Link href="/progress">Progress</Link>
              </div>
            </nav>
            <AuthBootstrap />
            {children}
          </ToastProvider>
        </Providers>
      </body>
    </html>
  );
}
