server:
  port: 8080

spring:
  application:
    name: bubbles-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bubbles}
    username: ${SPRING_DATASOURCE_USERNAME:bubbles}
    password: ${SPRING_DATASOURCE_PASSWORD:bubbles}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        options:
          model: ${OPENAI_MODEL:gpt-4o-mini}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"

security:
  jwt:
    secret: ${JWT_SECRET:dev-secret-change-me}
    issuer: bubbles
    expirationMinutes: 120


